# key bindings
left: shift h
right: shift l
up: shift k
down: shift j
left_fast: shift y
right_fast: shift o
up_fast: shift i
down_fast: shift u
zoom_in: ctrl k
zoom_out: ctrl j
zoom_in_fast: ctrl o
zoom_out_fast: ctrl i
remove: backspace
peel: space
dump: shift m
center: shift c
quick_place: lshift
cut: shift d
paste: shift p
flip: shift f
scramble_tiles: f1
sort_tiles: f2
count_tiles: f3
stack_tiles: f4
